name: redux_sandbox
description: A sandbox for Redux in Flutter.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^0.14.1
  # swapi_client: ^0.1.0

  flutter_redux: ^0.7.0
  # redux_dev_tools: ^0.5.2
  # redux_epics: ^0.14.0
  # redux_logging: ^0.4.0
  # redux_thunk: ^0.3.0
  redux: ^5.0.0
  # reselect: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter pub run build_runner watch
  # flutter pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^1.12.1
  freezed: ^0.14.1
  json_serializable: ^4.0.3

dependency_overrides:
  build_runner: ^1.11.5
  freezed_annotation: ^0.12.0
  freezed: ^0.12.7
  json_serializable: ^3.5.1
  redux: ^4.0.0+3

flutter:
  uses-material-design: true
